### ISSUE TITLE
can not get full props in Componet.props

### ISSUE THREAD

**Issue by njleonzhang** [jackmellis/vue-hoc#12]
https://github.com/jackmellis/vue-hoc/blob/ec91d6bb0b17e4ed289a87f21aa5856806b13332/src/createHOC.js#L25-L27

You can not get full `props` in `Componet.props` due to the exist of `mixin` or `extend`. 
But props can pass to the `inner Component` correctly by process options in running time.
So should we remove these lines?

**Comment by jackmellis** [comment]
I'm not sure I fully follow your train of thought here. Are you saying because your hoc won't include mixins/extended props, we should just ignore them?

Keep in mind that a lot of Vue's behaviour is depnedent on statically declaring your component's props so I'm not sure if this is a good idea, especially when trying to do advanced things like chaining multiple hocs together.

Let me know if I've misunderstood your explanation.

**Comment by njleonzhang** [comment]
Sorry for my poor EN.
You assign the `Component`'s props to HOC. but if the `Component` has `mixin`, then the amount of HOC props is less then the `Component`'s.

For example: 
```
let Component = {
   props: {prop1: String},
   mixins: [
     {
        props: {
          prop2: Boolean
        }
     }
   ]
}

let hoc = createHOC(Component)
```
HOC's props will be `prop1`. The `Component`'s props is `porp1` and `prop2` after Vue merging.

In this scenario, pass `prop2` to HOC can still work because HOC handle it as a `attr` in render function. So I think maybe we can remove this props assign, because `attr` can also make the HOC work.

I am new to Vue HOC, and not sure if I am right. 
I made a [HOC](https://gist.github.com/njleonzhang/248ac62deaff2ce9ceaf8119cba115a6) according my thought, it works currently.

**Comment by jackmellis** [comment]
So this essentially forces you to use `this.$attrs` and `this.$props` in order to access the props within your HOC.

Having the static `props` object populated means you a) can be explicit about your props and b) can access props in your HOC via `this.myProp`. Keep in mind that Vue is quite big on statically-declared props so personally I think we shouldn't just abandon this when creating HOCs in Vue.

Removing this functionality would also mean quite a big breaking change to vue-hoc, and I'm still entirely sure what advantage it gives you since, in theory, you would still be able to use `$props` and `$attrs` whether this code exists or not. Correct?

I think maybe the issue here should be more about whether the static props should be kept up to date with the runtime props - and to be honest I'm not sure whether it should (or if it could even be done).

I've written a quick example of what I think would do the same as your gist example. I haven't tested it or anything: https://gist.github.com/jackmellis/a8aa87fddc23054f98153654ab6d7fb8

**Comment by njleonzhang** [comment]
@jackmellis Your code should be able to work. 
As I mentioned in this example, the `hoc` you get do not have same `props` with `Component`. This's my point. 
 I know `prop` is good, it will be great if we can make `hoc` always have same `props` to `Component`. But it's not easy and may bring performance downgrade. 

```
let Component = {
   props: {prop1: String},
   mixins: [
     {
        props: {
          prop2: Boolean
        }
     }
   ]
}

let hoc = createHOC(Component)
```

Anyway, thanks very much for this tools. It's not easy for Vue to support HOC(attrs, props, event....). HOC is so elegant to replace `mixin`, I can not believe Vue team cliam that we don't intend to include a way to create HOC's into core, ***mainly because we don't see a large benefit over mixins / Extends.***

**Comment by jackmellis** [comment]
I think the argument against mixins is fairly abstract (i.e. it's about *ideal* practices rather than functional limitations) so I like to think of Vue HOCs to be an alternative rather than a replacement for them.

I'm not sure if there is an elegant solution to this. The current status is the static props contain props directly declared on the component. If you plan to use mixins/extends in your component heirarchy (and use hocs at the same time!) then you'll have to fall back to `this.$props.propFromMixin` instead.

I feel like trying to calculate all the possible permutations of what props may be dynamically added to the component - at composition time - would probably be too much overhead / too complicated for the current scope. I'm going to close this issue for now I think, unless I (or anybody) has a lightbulb moment...
