### ISSUE TITLE
Directives don't work with functional HOCs?

### ISSUE THREAD

**Issue by Dylan-Chapman** [jackmellis/vue-hoc#17]
I'm using Vuetify's VSelect component and wrapping it with some custom prop defaults. If the HOC is functional, the v-validate (via VeeValidate) directive doesn't work. Removing functional: true makes the validation work again. Is this a bug or a technical limitation?

**Comment by jackmellis** [comment]
I would imagine that this is related to [this issue](https://github.com/jackmellis/vue-hoc/issues/8). Basically it is a *lot* harder to write functional hocs in Vue and I'm hoping that someone from the core team (or someone with a brilliant idea) can offer a solution.

I generally point out that the advantage of using `functional` components in Vue is really quite negligible and when something doesn't work in a functional component, just make it non-functional! This is especially true when trying to create HOCs because you lose a lot of contextual data.

**Comment by Dylan-Chapman** [comment]
Fair enough! Will simply make components non-functional when I run into this problem.
