### ISSUE TITLE
Extra <template> tags

### ISSUE THREAD

**Issue by titouancreach** [jackmellis/vue-hoc#18]
I wish to make a withStyle HOC component to style my components. 

```javascript
import { createHOCc } from 'vue-hoc';

export function withStyle(style) {
  return createHOCc(null, {style});
};
```

Then I used it this way to create a red button:

```javascript
import {withStyle} from '../HOC/withStyle.js';

const style = {
  background: '#F00'
};

export default withStyle(style)('button');
```

The issue appears when I try to render it:

```jsx
import euiButton from '../UI/styledButton.jsx';

export default {
  components: {
    styledButton
  },

  render() {
    return (
      <v-app>
        <v-content>
          Hello World
          <styledButton>MyButton</styledButton>
        </v-content>
      </v-app>
    );
  }
};
```

In the dom, an extra pair of `<template>` is created: 

![screenshot at 2018-03-27 11-49-14](https://user-images.githubusercontent.com/3995719/37960078-ee3b0e02-31b4-11e8-8d51-f47c020ea7ee.png)

And my button doesn't appear. 

Why is this occurs ?

Thanks

**Comment by titouancreach** [comment]
It appears only with html elements

**Comment by jackmellis** [comment]
So out of curiosity what happens if you wrap your button text in an elemnet? i.e.
```
import euiButton from '../UI/styledButton.jsx';

export default {
  components: {
    styledButton
  },

  render() {
    return (
      <v-app>
        <v-content>
          Hello World
          <styledButton>
            <span>MyButton</span>
          </styledButton>
        </v-content>
      </v-app>
    );
  }
};
```

There was a [previous issue](https://github.com/jackmellis/vue-hoc/issues/11) for something similar but it was resolved. Perhaps there is still an issue.

**Comment by titouancreach** [comment]
With the span, the html is well generated :)

**Comment by jackmellis** [comment]
Yes. But the text content should still be rendering inside the Template, so it’s concerning that you say it isn’t...

**Comment by titouancreach** [comment]
The text **is** rendered ! but inside the <template> tag. (you can see in the screenshot)

**Comment by jackmellis** [comment]
I'm not entirely sure but I think the issue stems from Vue's own `<template>` component somehow.

For some reason, if a slot contains some plain text, it can't render it alongside another element (i.e. `<MyComponent><span>an element</span> and some text</MyComponent>`). It simply just falls over.

The current solution is that if your slot contains a text node, it wraps the whole thing in a `<template>`. This seems to work find if your component is an actual component (i.e. `<MyComponent>`) but if you pass in a html element to the render function (i.e. `"button"`) it again can't seem to handle it.

The only way I can seem to satisfy all conditions is if I wrap it in an _actual_ element like a `<span>`. This would mean that `<span>some element</span> and some text` would be rendered as `<span><span>some element</span> and some text</span>`. This isn't idea because it's adding hidden markup to your page (which I'd really like to avoid). But I can't find another way around this.

I'm going to put up a potential fix with a view to getting some useful advice on the matter.

**Comment by titouancreach** [comment]
Maybe we should just admit that Vue is not made for HOC, cry in a corner and use mixins :|
Thanks anyway for the information 👍

**Comment by ysaaron** [comment]
In #19 [packages/vue-hoc/src/normalizeSlots.js#L10](https://github.com/jackmellis/vue-hoc/pull/19/files#diff-477cd72426761e1fc5e499abf062ab26R10), I've pulled [fix/html-component-slots](https://github.com/jackmellis/vue-hoc/tree/fix/html-component-slots) and reproduce this issue, even though I remove the line detecting whether it is text node also woking profect.

**Comment by ysaaron** [comment]
In #19 [packages/vue-hoc/src/normalizeSlots.js#L10](https://github.com/jackmellis/vue-hoc/pull/19/files#diff-477cd72426761e1fc5e499abf062ab26R10), I've pulled [fix/html-component-slots](https://github.com/jackmellis/vue-hoc/tree/fix/html-component-slots) and reproduce this issue,

Even though I remove the line detecting whether it is text node also woking perfect in this issue and normal condition. I think it is not required to detect whether node is text or not.

**Comment by jackmellis** [comment]
Can you create another PR showing what you've done please? =)
