### ISSUE TITLE
Props are rendered to the DOM

### ISSUE THREAD

**Issue by Dylan-Chapman** [jackmellis/vue-hoc#25]
Whenever a prop is attached to a HOC, it is rendered to the DOM. For example, if I'm using a HOC for Vuetify's ```VDataTable``` component, I see this if I inspect the DOM:

```html
<div data-v-a0f8bd1c="" items="[object Object],[object Object],[object Object],[object Object]" pagination="[object Object]" hide-actions="" must-sort="">
...
```

Is there any way do avoid this?

**Comment by Dylan-Chapman** [comment]
The problem persists even with a setup as simple as:

```javascript
export default createHOC( VDataTable );
```

And the props that were placed onto the DOM element shown above (items, pagination, hide-actions, must-sort) are props that are defined on Vuetify's ```VDataTable```. However, I had more props attached to my HOC than the four listed. I guess the props that are placed into the DOM are props that come from mixins on ```VDataTable```.

**Comment by jackmellis** [comment]
For reference, the problem lies [here](https://github.com/jackmellis/vue-hoc/blob/master/packages/vue-hoc/src/createRenderFn.js#L100)

We try to work out which props are not declared on the base component and then assign those as attributes instead. The problem is definitely mixin related. It may be possible (with a little overhead) to manually work out what props are provided by mixins and take that into account. But then you've got global mixins which really messes things up.
